# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-20 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default='2018-07-20 10:16:30.828000+00:00')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default='2018-07-20 10:16:30.830000+00:00')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default='2018-07-20 10:16:30.830000+00:00')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='exercises/')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='public.Exercise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default='2018-07-20 10:16:30.830000+00:00')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkoutWithExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default='2018-07-20 10:16:30.830000+00:00')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts_with_exercises', to='public.Exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts_with_exercises', to='public.Workout')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutWithGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default='2018-07-20 10:16:30.831000+00:00')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts_with_groups', to='public.Group')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts_with_groups', to='public.Workout')),
            ],
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(related_name='workouts', through='public.WorkoutWithExercise', to='public.Exercise'),
        ),
        migrations.AddField(
            model_name='workout',
            name='groups',
            field=models.ManyToManyField(related_name='workouts', through='public.WorkoutWithGroup', to='public.Group'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='public.Group'),
        ),
        migrations.AlterUniqueTogether(
            name='workoutwithgroup',
            unique_together=set([('group', 'workout')]),
        ),
        migrations.AlterUniqueTogether(
            name='workoutwithexercise',
            unique_together=set([('exercise', 'workout')]),
        ),
    ]
