# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-20 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20181219_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutwithexercise',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='workoutwithexercise',
            unique_together=set([('workout', 'order'), ('exercise', 'workout')]),
        ),
    ]
