# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-16 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20181220_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
