# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2021-01-30 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_workout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
